### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by anulin** [telatin/metaprokka#2]
Hello!

I tried installing metaprokka to a conda environment with installed prokka but get an error. The comment is:

- feature:/linux-64::__glibc==2.17=0 - feature:|@/linux-64::__glibc==2.17=0

When I tried to set up a new environment for metaprokka I also got this error

**Comment by telatin** [comment]
Hello @anulin !
Thanks for reporting this. I'll make a couple of trials and let you know

**Comment by telatin** [comment]
I tried, using mamba 1.3.1 and conda 23.1.0, and
```bash
mamba create -n metap -c conda-forge -c bioconda metaprokka
```
worked for me.

Did you specify conda-forge as a channel as well?

**Comment by anulin** [comment]
okay adding -c conda-forge helped, thank you!
